# Image source code: https://github.com/axonasif/workspace-images/tree/tmp
# Also see: https://github.com/gitpod-io/workspace-images/issues/1071
image: axonasif/workspace-python@sha256:f5ba627a31505ea6cf100abe8e552d7ff9e0abd6ba46745b6d6dab349c001430

tasks:
  - name: Init project and run server
    init: |
      PROJECT_NAME="flaskr"

      if test ! -e "${PROJECT_NAME}"; then {
        tmp_dir=/tmp/.fgc
        git clone --filter=tree:0 https://github.com/pallets/flask "${tmp_dir}"
        mv "${tmp_dir}/examples/tutorial"/{.*,*} . 2>/dev/null
        rm -rf "${tmp_dir}"
      } fi

      pip install -e .
      if test -e "${PROJECT_NAME}"; then {
        flask --app "${PROJECT_NAME}" init-db
      } fi

    command: |
      PROJECT_NAME="flaskr"

      flask --app "${PROJECT_NAME}" run --debug

ports:
  - port: 5000
    onOpen: open-preview
    description: Flask App preview

vscode:
  extensions:
    - ms-python.python

